/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function populatedb() {
    
    var sql_drop_fnames = "DROP TABLE IF EXISTS fnames";
    var sql_drop_lnames = "DROP TABLE IF EXISTS lnames";
    var sql_create_fnames = "CREATE TABLE fnames (fnid INTEGER PRIMARY KEY, fname TEXT)";
    var sql_create_lnames = "CREATE TABLE lnames (lnid INTEGER PRIMARY KEY, lname TEXT)";

    var db = sqlitePlugin.openDatabase({name: "names.db"});

    db.transaction(function (tx) {

        tx.executeSql(sql_drop_fnames);
        tx.executeSql(sql_drop_lnames);
        tx.executeSql(sql_create_fnames);
        tx.executeSql(sql_create_lnames);
//        tx.executeSql("INSERT INTO fnames VALUES(1,'Mark')");
//        tx.executeSql("INSERT INTO fnames VALUES(2,'Vincent')");
//        tx.executeSql("INSERT INTO fnames VALUES(3,'Eduardo')");
//        tx.executeSql("INSERT INTO fnames VALUES(4,'Bernard')");
//        tx.executeSql("INSERT INTO fnames VALUES(5,'Paolo')");
//        tx.executeSql("INSERT INTO fnames VALUES(6,'John')");
//        tx.executeSql("INSERT INTO fnames VALUES(7,'Christopher')");
//        tx.executeSql("INSERT INTO fnames VALUES(8,'Alvin')");
//        tx.executeSql("INSERT INTO fnames VALUES(9,'Jerick')");
//        tx.executeSql("INSERT INTO fnames VALUES(10,'Dennis')");
//        tx.executeSql("INSERT INTO fnames VALUES(11,'Richard')");
//        tx.executeSql("INSERT INTO fnames VALUES(12,'Jerico')");
//        tx.executeSql("INSERT INTO fnames VALUES(13,'Ralph')");
//        tx.executeSql("INSERT INTO fnames VALUES(14,'Louie')");
//        tx.executeSql("INSERT INTO fnames VALUES(15,'Emil')");
//        tx.executeSql("INSERT INTO fnames VALUES(16,'Christian')");
//        tx.executeSql("INSERT INTO fnames VALUES(17,'Ritchie')");
//        tx.executeSql("INSERT INTO fnames VALUES(18,'Maximino')");
//        tx.executeSql("INSERT INTO fnames VALUES(19,'Ernest')");
//        tx.executeSql("INSERT INTO fnames VALUES(20,'Freddie Boy')");
//        tx.executeSql("INSERT INTO fnames VALUES(21,'Ian')");
//        tx.executeSql("INSERT INTO fnames VALUES(22,'Lester')");
//        tx.executeSql("INSERT INTO fnames VALUES(23,'Ivan')");
//        tx.executeSql("INSERT INTO fnames VALUES(24,'Efren')");
//        tx.executeSql("INSERT INTO fnames VALUES(25,'Leo')");
//        tx.executeSql("INSERT INTO fnames VALUES(26,'Ariel')");
//        tx.executeSql("INSERT INTO fnames VALUES(27,'Jeremiah')");
//        tx.executeSql("INSERT INTO fnames VALUES(28,'Glen')");
//        tx.executeSql("INSERT INTO fnames VALUES(29,'Paul')");
//        tx.executeSql("INSERT INTO fnames VALUES(30,'Ryan')");
//        tx.executeSql("INSERT INTO fnames VALUES(31,'Francis')");
//        tx.executeSql("INSERT INTO fnames VALUES(32,'Herbert')");
//        tx.executeSql("INSERT INTO fnames VALUES(33,'Kenneth')");
//        tx.executeSql("INSERT INTO fnames VALUES(34,'Marco')");
//        tx.executeSql("INSERT INTO fnames VALUES(35,'Carlo')");
//        tx.executeSql("INSERT INTO fnames VALUES(36,'Joseph')");
//        tx.executeSql("INSERT INTO fnames VALUES(37,'Marvin')");
//        tx.executeSql("INSERT INTO fnames VALUES(38,'Clint')");
//        tx.executeSql("INSERT INTO fnames VALUES(39,'Nathan')");
//        tx.executeSql("INSERT INTO fnames VALUES(40,'Michael')");
//        tx.executeSql("INSERT INTO fnames VALUES(41,'Gideon')");
//        tx.executeSql("INSERT INTO fnames VALUES(42,'Russell')");
//        tx.executeSql("INSERT INTO fnames VALUES(43,'Jayson')");
//        tx.executeSql("INSERT INTO fnames VALUES(44,'Denver')");
//        tx.executeSql("INSERT INTO fnames VALUES(45,'Manuel')");
//        tx.executeSql("INSERT INTO fnames VALUES(46,'Joey')");
//        tx.executeSql("INSERT INTO fnames VALUES(47,'Arnold')");
//        tx.executeSql("INSERT INTO fnames VALUES(48,'Dave')");
//        tx.executeSql("INSERT INTO fnames VALUES(49,'Kurt')");
//        tx.executeSql("INSERT INTO fnames VALUES(50,'Ramon')");
//        tx.executeSql("INSERT INTO fnames VALUES(51,'Richmond')");
//        tx.executeSql("INSERT INTO fnames VALUES(52,'Aldrin')");
//        tx.executeSql("INSERT INTO fnames VALUES(53,'Sherwin')");
//        tx.executeSql("INSERT INTO fnames VALUES(54,'Floyd')");
//        tx.executeSql("INSERT INTO fnames VALUES(55,'Henry')");
//        tx.executeSql("INSERT INTO fnames VALUES(56,'Jefferson')");
//        tx.executeSql("INSERT INTO fnames VALUES(57,'Eliezer')");
//        tx.executeSql("INSERT INTO fnames VALUES(58,'Edwin')");
//        tx.executeSql("INSERT INTO fnames VALUES(59,'Jordan')");
//        tx.executeSql("INSERT INTO fnames VALUES(60,'James')");
//        tx.executeSql("INSERT INTO fnames VALUES(61,'Tom')");
//        tx.executeSql("INSERT INTO fnames VALUES(62,'Victor')");
//        tx.executeSql("INSERT INTO fnames VALUES(63,'Jerome')");
//        tx.executeSql("INSERT INTO fnames VALUES(64,'Lorence')");
//        tx.executeSql("INSERT INTO fnames VALUES(65,'Wendell')");
//        tx.executeSql("INSERT INTO fnames VALUES(66,'Jorge')");
//        tx.executeSql("INSERT INTO fnames VALUES(67,'Marlon')");
//        tx.executeSql("INSERT INTO fnames VALUES(68,'Rolando')");
//        tx.executeSql("INSERT INTO fnames VALUES(69,'Tomas')");
//        tx.executeSql("INSERT INTO fnames VALUES(70,'Ruel')");
//        tx.executeSql("INSERT INTO fnames VALUES(71,'Brandon')");
//        tx.executeSql("INSERT INTO fnames VALUES(72,'Allan')");
//        tx.executeSql("INSERT INTO fnames VALUES(73,'Randy')");
//        tx.executeSql("INSERT INTO fnames VALUES(74,'Harold')");
//        tx.executeSql("INSERT INTO fnames VALUES(75,'Jaynard')");
//        tx.executeSql("INSERT INTO fnames VALUES(76,'Ronick')");
//        tx.executeSql("INSERT INTO fnames VALUES(77,'Elmer')");
//        tx.executeSql("INSERT INTO fnames VALUES(78,'Darwin')");
//        tx.executeSql("INSERT INTO fnames VALUES(79,'Bryan')");
//        tx.executeSql("INSERT INTO fnames VALUES(80,'Jeffrey')");
//        tx.executeSql("INSERT INTO fnames VALUES(81,'Ken')");
//        tx.executeSql("INSERT INTO fnames VALUES(82,'Edgar')");
//        tx.executeSql("INSERT INTO fnames VALUES(83,'Oliver')");
//        tx.executeSql("INSERT INTO fnames VALUES(84,'Gerard')");
//        tx.executeSql("INSERT INTO fnames VALUES(85,'Jason')");
//        tx.executeSql("INSERT INTO fnames VALUES(86,'Edilberto')");
//        tx.executeSql("INSERT INTO fnames VALUES(87,'Rodolfo')");
//        tx.executeSql("INSERT INTO fnames VALUES(88,'Donald')");
//        tx.executeSql("INSERT INTO fnames VALUES(89,'Ernie')");
//        tx.executeSql("INSERT INTO fnames VALUES(90,'Philip')");
//        tx.executeSql("INSERT INTO fnames VALUES(91,'Sebastian')");
//        tx.executeSql("INSERT INTO fnames VALUES(92,'Gerald')");
//        tx.executeSql("INSERT INTO fnames VALUES(93,'Joepert')");
//        tx.executeSql("INSERT INTO fnames VALUES(94,'Eddie')");
//        tx.executeSql("INSERT INTO fnames VALUES(95,'Hero')");
//        tx.executeSql("INSERT INTO fnames VALUES(96,'Pocholo')");
//        tx.executeSql("INSERT INTO fnames VALUES(97,'Ricardo')");
//        tx.executeSql("INSERT INTO fnames VALUES(98,'Roderick')");
//        tx.executeSql("INSERT INTO fnames VALUES(99,'Gabby')");
//        tx.executeSql("INSERT INTO fnames VALUES(100,'Patrick')");
//        tx.executeSql("INSERT INTO fnames VALUES(101,'Albano')");
//        tx.executeSql("INSERT INTO fnames VALUES(102,'Julius')");
//        tx.executeSql("INSERT INTO fnames VALUES(103,'Lyndon')");
//        tx.executeSql("INSERT INTO fnames VALUES(104,'Daniel')");
//        tx.executeSql("INSERT INTO fnames VALUES(105,'Aaron')");
//        tx.executeSql("INSERT INTO fnames VALUES(106,'Noly')");
//        tx.executeSql("INSERT INTO fnames VALUES(107,'Raul')");
//        tx.executeSql("INSERT INTO fnames VALUES(108,'Alwin')");
//        tx.executeSql("INSERT INTO fnames VALUES(109,'Angelo')");
//        tx.executeSql("INSERT INTO fnames VALUES(110,'Frank')");
//        tx.executeSql("INSERT INTO fnames VALUES(111,'Rodel')");
//        tx.executeSql("INSERT INTO fnames VALUES(112,'Alfred')");
//        tx.executeSql("INSERT INTO fnames VALUES(113,'Renz')");
//        tx.executeSql("INSERT INTO fnames VALUES(114,'Armando')");
//        tx.executeSql("INSERT INTO fnames VALUES(115,'Rafael')");
//        tx.executeSql("INSERT INTO fnames VALUES(116,'Robbie')");
//        tx.executeSql("INSERT INTO fnames VALUES(117,'Arthur')");
//        tx.executeSql("INSERT INTO fnames VALUES(118,'Ezekiel')");
//        tx.executeSql("INSERT INTO fnames VALUES(119,'Harvey')");
//        tx.executeSql("INSERT INTO fnames VALUES(120,'Jonathan')");
//        tx.executeSql("INSERT INTO fnames VALUES(121,'Ulysses')");
//        tx.executeSql("INSERT INTO fnames VALUES(122,'Almonte')");
//        tx.executeSql("INSERT INTO fnames VALUES(123,'Noel')");
//        tx.executeSql("INSERT INTO fnames VALUES(124,'Giovanni')");
//        tx.executeSql("INSERT INTO fnames VALUES(125,'Menardo')");
//        tx.executeSql("INSERT INTO fnames VALUES(126,'Anthony')");
//        tx.executeSql("INSERT INTO fnames VALUES(127,'Albert')");
//        tx.executeSql("INSERT INTO fnames VALUES(128,'Antonio')");
//        tx.executeSql("INSERT INTO fnames VALUES(129,'Bimbo')");
//        tx.executeSql("INSERT INTO fnames VALUES(130,'Jim')");
//        tx.executeSql("INSERT INTO fnames VALUES(131,'Wilson')");
//        tx.executeSql("INSERT INTO fnames VALUES(132,'Earl')");
//        tx.executeSql("INSERT INTO fnames VALUES(133,'Florence')");
//        tx.executeSql("INSERT INTO fnames VALUES(134,'Lawrence')");
//        tx.executeSql("INSERT INTO fnames VALUES(135,'Chester')");
//        tx.executeSql("INSERT INTO fnames VALUES(136,'Andrew')");
//        tx.executeSql("INSERT INTO fnames VALUES(137,'Luigi')");
//        tx.executeSql("INSERT INTO fnames VALUES(138,'Marvic')");
//        tx.executeSql("INSERT INTO fnames VALUES(139,'Emmanuel')");
//        tx.executeSql("INSERT INTO fnames VALUES(140,'Gabriel')");
//        tx.executeSql("INSERT INTO fnames VALUES(141,'Roberto')");
//        tx.executeSql("INSERT INTO lnames VALUES(1,'Abad')");
//        tx.executeSql("INSERT INTO lnames VALUES(2,'Abadia')");
//        tx.executeSql("INSERT INTO lnames VALUES(3,'Abadilla')");
//        tx.executeSql("INSERT INTO lnames VALUES(4,'Abalos')");
//        tx.executeSql("INSERT INTO lnames VALUES(5,'Abao')");
//        tx.executeSql("INSERT INTO lnames VALUES(6,'Abarientos')");
//        tx.executeSql("INSERT INTO lnames VALUES(7,'Abarquez')");
//        tx.executeSql("INSERT INTO lnames VALUES(8,'Abaya')");
//        tx.executeSql("INSERT INTO lnames VALUES(9,'Abaygar')");
//        tx.executeSql("INSERT INTO lnames VALUES(10,'Abejar')");
//        tx.executeSql("INSERT INTO lnames VALUES(11,'Abelarde')");
//        tx.executeSql("INSERT INTO lnames VALUES(12,'Abelardo')");
//        tx.executeSql("INSERT INTO lnames VALUES(13,'Abellana')");
//        tx.executeSql("INSERT INTO lnames VALUES(14,'Bernardo')");
//        tx.executeSql("INSERT INTO lnames VALUES(15,'Abendan')");
//        tx.executeSql("INSERT INTO lnames VALUES(16,'Abesamis')");
//        tx.executeSql("INSERT INTO lnames VALUES(17,'Abiog')");
//        tx.executeSql("INSERT INTO lnames VALUES(18,'Abraham')");
//        tx.executeSql("INSERT INTO lnames VALUES(19,'Abrera')");
//        tx.executeSql("INSERT INTO lnames VALUES(20,'Abueva')");
//        tx.executeSql("INSERT INTO lnames VALUES(21,'Acedillo')");
//        tx.executeSql("INSERT INTO lnames VALUES(22,'Acevedo')");
//        tx.executeSql("INSERT INTO lnames VALUES(23,'Acharon')");
//        tx.executeSql("INSERT INTO lnames VALUES(24,'Acosta')");
//        tx.executeSql("INSERT INTO lnames VALUES(25,'Acuesta')");
//        tx.executeSql("INSERT INTO lnames VALUES(26,'Adlawan')");
//        tx.executeSql("INSERT INTO lnames VALUES(27,'Adriano')");
//        tx.executeSql("INSERT INTO lnames VALUES(28,'Advincula')");
//        tx.executeSql("INSERT INTO lnames VALUES(29,'Afable')");
//        tx.executeSql("INSERT INTO lnames VALUES(30,'Agapito')");
//        tx.executeSql("INSERT INTO lnames VALUES(31,'Agbayani')");
//        tx.executeSql("INSERT INTO lnames VALUES(32,'Agcaoili')");
//        tx.executeSql("INSERT INTO lnames VALUES(33,'Aglipay')");
//        tx.executeSql("INSERT INTO lnames VALUES(34,'Agno')");
//        tx.executeSql("INSERT INTO lnames VALUES(35,'Aguado')");
//        tx.executeSql("INSERT INTO lnames VALUES(36,'Aguas')");
//        tx.executeSql("INSERT INTO lnames VALUES(37,'Aguila')");
//        tx.executeSql("INSERT INTO lnames VALUES(38,'Aguilar')");
//        tx.executeSql("INSERT INTO lnames VALUES(39,'Aguinaldo')");
//        tx.executeSql("INSERT INTO lnames VALUES(40,'Aguirre')");
//        tx.executeSql("INSERT INTO lnames VALUES(41,'Agustin')");
//        tx.executeSql("INSERT INTO lnames VALUES(42,'Alano')");
//        tx.executeSql("INSERT INTO lnames VALUES(43,'Alarcon')");
//        tx.executeSql("INSERT INTO lnames VALUES(44,'Alba')");
//        tx.executeSql("INSERT INTO lnames VALUES(45,'Albano')");
//        tx.executeSql("INSERT INTO lnames VALUES(46,'Alberto')");
//        tx.executeSql("INSERT INTO lnames VALUES(47,'Alcala')");
//        tx.executeSql("INSERT INTO lnames VALUES(48,'Alcantara')");
//        tx.executeSql("INSERT INTO lnames VALUES(49,'Alcaraz')");
//        tx.executeSql("INSERT INTO lnames VALUES(50,'Aldana')");
//        tx.executeSql("INSERT INTO lnames VALUES(51,'Aldecoa')");
//        tx.executeSql("INSERT INTO lnames VALUES(52,'Aldeguer')");
//        tx.executeSql("INSERT INTO lnames VALUES(53,'Alegre')");
//        tx.executeSql("INSERT INTO lnames VALUES(54,'Alegria')");
//        tx.executeSql("INSERT INTO lnames VALUES(55,'Alejandrino')");
//        tx.executeSql("INSERT INTO lnames VALUES(56,'Alejandro')");
//        tx.executeSql("INSERT INTO lnames VALUES(57,'Alejo')");
//        tx.executeSql("INSERT INTO lnames VALUES(58,'Alfaro')");
//        tx.executeSql("INSERT INTO lnames VALUES(59,'Alfonso')");
//        tx.executeSql("INSERT INTO lnames VALUES(60,'Alipio')");
//        tx.executeSql("INSERT INTO lnames VALUES(61,'Almario')");
//        tx.executeSql("INSERT INTO lnames VALUES(62,'Almazan')");
//        tx.executeSql("INSERT INTO lnames VALUES(63,'Almeda')");
//        tx.executeSql("INSERT INTO lnames VALUES(64,'Alonzo')");
//        tx.executeSql("INSERT INTO lnames VALUES(65,'Alunan')");
//        tx.executeSql("INSERT INTO lnames VALUES(66,'Alvarado')");
//        tx.executeSql("INSERT INTO lnames VALUES(67,'Alvarez')");
//        tx.executeSql("INSERT INTO lnames VALUES(68,'Amador')");
//        tx.executeSql("INSERT INTO lnames VALUES(69,'Amante')");
//        tx.executeSql("INSERT INTO lnames VALUES(70,'Anastacio')");
//        tx.executeSql("INSERT INTO lnames VALUES(71,'Ancheta')");
//        tx.executeSql("INSERT INTO lnames VALUES(72,'Andal')");
//        tx.executeSql("INSERT INTO lnames VALUES(73,'Barrientos')");
//        tx.executeSql("INSERT INTO lnames VALUES(74,'Belen')");
//        tx.executeSql("INSERT INTO lnames VALUES(75,'Borja')");
//        tx.executeSql("INSERT INTO lnames VALUES(76,'Castro')");
//        tx.executeSql("INSERT INTO lnames VALUES(77,'Cervantes')");
//        tx.executeSql("INSERT INTO lnames VALUES(78,'Dominguez')");
//        tx.executeSql("INSERT INTO lnames VALUES(79,'De Leon')");
//        tx.executeSql("INSERT INTO lnames VALUES(80,'Ferrer')");
//        tx.executeSql("INSERT INTO lnames VALUES(81,'Galvez')");
//        tx.executeSql("INSERT INTO lnames VALUES(82,'Gavino')");
//        tx.executeSql("INSERT INTO lnames VALUES(83,'Hipolito')");
//        tx.executeSql("INSERT INTO lnames VALUES(84,'Hernandez')");
//        tx.executeSql("INSERT INTO lnames VALUES(85,'Mendez')");
//        tx.executeSql("INSERT INTO lnames VALUES(86,'Natividad')");

    });
}